version: '3.1'
services:

  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwdmuntant
    ports:
      - 3306:3306
    expose:
      - 3306

  mutant:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DATABASE_HOST: db
      DB_NAME: "root"
      DB_PASSWORD: "pwdmuntant"
      DB_DATABASE: "mutant_log"
    ports:
      - 3000:3000
    depends_on:
      - db