version: '3.1'
services:
  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwdmuntant
    volumes:
      - 'db:/docker-entrypoint-initdb.d'
      - 'data:/var/lib/mysql'
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'

  mutant:
      dockerfile: Dockerfile
      restart: always
      environment:
        DB_HOST: mysql
        DB_NAME: "root"
        DB_PASSWORD: "pwdmuntant"
        DB_DATABASE: "mutant_log"
      ports:
        - 3000:3000
      depends_on:
        - mysql